#!/usr/bin/python

import sys

def main():
    # print command line arguments
    for arg in sys.argv[1:]:
        print arg
# sys.argv[0] is the name of the files and 1,2... are the following arguments


if __name__ == "__main__":
    main()
